name: Java CI Practice

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      -main

  workflow_dispatch:



jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Check Java version
        run: java -version

      - name: Compile Java code
        run: javac src/main.java

      - name: Run Java program
        run: |
          java -cp src main > output.txt

      - name: Show output
        run: cat output.txt

      - name: Upload output artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-program-output
          path: output.txt